name: Python Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: playwright install
      
      - name: Run Pytest Tests and generate HTML report
        run: |
          mkdir -p reports
          pytest --maxfail=1 --disable-warnings -v --html=reports/report.html --self-contained-html
          
      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/
          retention-days: 30
      
      - name: Upload Playwright Videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: videos/
          retention-days: 30
